<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>InfiniteInventory</AssemblyName>
    <Product>InfiniteInventory</Product>
    <RootNamespace>InfiniteInventory</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\_lib\Assembly-CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
