<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>MapTraveller</AssemblyName>
    <Product>MapTraveller</Product>
    <RootNamespace>MapTraveller</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\_lib\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="better">
      <HintPath>..\_lib\better.dll</HintPath>
    </Reference>
    <Reference Include="pixelliner">
      <HintPath>..\_lib\pixelliner.dll</HintPath>
    </Reference>
    <Reference Include="unsafeAssem">
      <HintPath>..\_lib\unsafeAssem.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
