<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Demosaic</AssemblyName>
    <Product>Demosaic</Product>
    <RootNamespace>Demosaic</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\_lib\Assembly-CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
